// 底tab图标
import '../svgFolder/teb_souye_normal.svg';
import '../svgFolder/teb_souye_selected.svg';
import '../svgFolder/teb_yingyong_normal.svg';
import '../svgFolder/teb_yingyong_selected.svg';
import '../svgFolder/teb_tongxunl_selected.svg';
import '../svgFolder/teb_tongxunl_normal.svg';
import '../svgFolder/teb_wode_normal.svg';
import '../svgFolder/teb_wode_selected.svg';
